<?php 
/**
* 
*/
class model_etudiants extends CI_Model
{
    public function get_list_by_niv($niveau,$inscrit='1')
    {
        $this->db->where('niveau',$niveau);
        $this->db->where('inscrit',$inscrit);
        $query = $this->db->get('etudiant');
        return $query->result();
	}
    public function get_all()
    {
        $this->db->where('old','f');
        $this->db->where('inscrit',1);
        $query = $this->db->get('etudiant');
        return $query->result();
    }
    /**
     * @param $niv1
     * @param string $inscrit
     * @return Liste Etudiant Niveau 1 et 2
     */
    public function get_list_etudiant($niv1, $inscrit='1',$nivsup=true)
	{
	    if($inscrit=='1' || $inscrit=='0'){
            $this->db->where('inscrit',$inscrit);
        }
        if ($nivsup==true){
            $niv2 = get_niv2($niv1);
            $this->db->where("(niveau='".$niv1."' OR niveau='".$niv2."')");
        }else{
            $this->db->where('niveau',$niv1);
        }
		$this->db->order_by("inscrit", "asc");
		$this->db->order_by("niveau,etat,id_etudiant", "asc");
		$query=$this->db->get('etudiant');
		return $query->result();
	}
    public function get_decision($idet,$niveau)
    {
        $this->db->where('id_etudiant',$idet);
        $this->db->where('niveau_des',$niveau);
        $query = $this->db->get('decision');
        return $query->row();
    }

    public function get_listEtudiantByDecision($niveau,$decision,$annee)
    {
        if ($decision=='EXP'){
            $decision = 'AJN';
        }
        $this->db->select('etudiant.id_etudiant,nom,prenom,niveau,decision,decision.annee_etude');
        $this->db->where('niveau_des',$niveau);
        $this->db->where('decision',$decision);
        $this->db->where('decision.annee_etude',$annee);
        $this->db->order_by('nom','ASC');
        $this->db->from('etudiant');
        $this->db->join('decision','decision.id_etudiant= etudiant.id_etudiant');

        $q = $this->db->get();
        return $q->result();
    }
    public function get_matiereRat($idet)
    {
        $this->db->select('resultat,nom_matiere,resultat_matiere.id_unite');
        $this->db->from('resultat_matiere');
        $this->db->join('matiere','matiere.id_matiere=resultat_matiere.id_matiere');
        $this->db->where('id_etudiant',$idet);
        $this->db->where('resultat','AJN');
        $query = $this->db->get();
        return $query->result();

    }
	public function get_info_etudiant($id,$table="etudiant")
	{
		$this->db->where('id_etudiant',$id);
		$query=$this->db->get($table);
        return $query->row();
	}
	public function get_sexe_etudiant($sexe,$nom,$prenom)
    {
        if ($sexe=="masculin"){
            $result= "Monsieur: ".$nom." ".$prenom;
        }else{
            $result= "Mademoiselle: ".$nom." ".$prenom;
        }
        return $result;
    }
    public function get_naissance($key)
    {
        return parent::__get($key); // TODO: Change the autogenerated stub
    }

    public function insert($param)
    {
        //CHECK
        $query = $this->db->get_where('etudiant',array('id_etudiant'=>$param['id']));
        $check = $query->num_rows();
        $error =array();
        if ($check ==0){
            //NOM et PRENOM
            if (empty($param['nom']) || empty($param['prenom'])){
                $error['nom'] = 'Le nom ou prénom ne doit pas être vide';
            }
            //SEXE
            if ($param['sexe'] =='h' || $param['sexe'] =='H'){
                $param['sexe'] = 'masculin';
            }
            if ($param['sexe'] =='f' || $param['sexe'] =='F'){
                $param['sexe'] = 'feminin';
            }
            $param['sexe'] = strtolower(str_replace('é','e',$param['sexe']));
            if ($param['sexe']!= 'masculin' && $param['sexe']!= 'feminin'){
                $error['sexe']= 'Sexe non valide';
            }
        }else{
            $error['exist'] = "Cet étudiant existe ({$param['nom']} {$param['prenom']})";
        }
        //INSERT
        if (empty($error)){
            $this->db->set('id_etudiant',$param['id']);
            $this->db->set('nom',$param['nom']);
            $this->db->set('prenom',$param['prenom']);
            $this->db->set('sexe',$param['sexe']);
            $this->db->set('naissance',$param['date']);
            $this->db->set('lieu',$param['lieu']);
            $this->db->set('adresse',$param['adresse']);
            $this->db->set('telephone',$param['phone']);
            $this->db->set('niveau','L1');
            $this->db->set('annee_etude',$_SESSION['annee_etude']);

            $this->db->insert('etudiant');
            return('OK');
        }else{
            return $error;
        }
        
    }

}
 ?>